### ISSUE TITLE
Switch async away from threaded - or at least permit/facilitate it

### ISSUE THREAD

**Issue by hedgehog** [andrewvc/dripdrop#11]
Hi very interesting.  Would you consider dropping use of Thread in node, or at least making it optional some require+include.  Alternatives are, I think, reactor pattern, or observer pattern.  Observer pattern is my interest.  Not sure yet how it would best work, but it would be neater and make the asynchronous behavior explicit, without making it tricky (if properly constrained).

Open to such an approach?

**Comment by andrewvc** [comment]
I actually always envisioned that as an option. My plan was to use the Node class for async and implement a threaded version along side it. Maybe I should rename Node to Async, and create a Threaded one.

In fact, what I'd really like to do is use Ilya Grigorik's Agent to use goroutines for concurrency. How's that sound to you?

I think it's not as simple as just dropping async from Node, Node looks evented (with all the callbacks) and acts evented. I don't think a threaded version should look that way. Also, there's some issues with closing sockets that using an async version kinda wallpapers over, though with ZMQ's upcoming 2.1.0 release that might all change.

I'm pretty open to having even more models of concurrency as long as the code's good. If you want, I'll be on freenode #zeromq tonight ~ 8PM pacific, we could chat there about the specifics if you'd like.

**Comment by hedgehog** [comment]
> In fact, what I'd really like to do is use Ilya Grigorik's Agent to use goroutines for concurrency. How's that sound to you?

Haven't we just moved the Thread.new to somewhere else.  Again I probably don't yet understand DripDrop, but I thought the idea was rather to use zmq for this sort of thing, so that you could, at init/start-up, change some key-value from inproc, to tcp and have your `go` code run on a different machine.  

> I think it's not as simple as just dropping async from Node

Sorry I was not clear.  Not suggesting dropping Async from Node, just the opposite.  Making it more async by allowing non-blocking behavior  via alternatives to thread.

> we could chat there about the specifics if you'd like.

Sorry I just saw this.  I'll dig into the code a little more, but before I invest time, I will likely ask your intentions on non-implementation issues, like:
- Will you be adopting a spec framework less than 1% of devs, use (e.g. Fog's Shindo)
- Will you be coding a complex piece of software, with even more complex behaviors, without any unit spec's and just some psuedo-integration "spec's" (e.g. Bundler)

Both are counter productive by keeping the dev base narrow (Fog), and making it extraordinarily difficult to add features, modify behavior (Bundler).

**Comment by andrewvc** [comment]
So, not in the cards.
