### ISSUE TITLE
Unified Naming

### ISSUE THREAD

**Issue by andrewvc** [andrewvc/dripdrop#16]
Hey guys, I'd like to fix any weird inconsistencies in naming in the API prior to our next gem release in a couple of days. I already pushed one change (renamed websocket to websocket_server) but would like to know if you guys see any other oddities.

One big change I'm thinking of is renaming :on_recv to :on_receive (the old method would work, but be deprecated and print a warning to $stderr). 

My reasoning is we should either have on_recv and send_msg, or on_receive and send_message. I'm favoring long names because other parts of the lib tend to use long names as well.

Thoughts?

**Comment by oruen** [comment]
+1 for long names

Other thing is an optional param `on_recv` instance method of `ZMQBaseHandler` and `HTTPServerHandler` accepts - `msg_format`. I don't see any usage for that local variable, only `@msg_format` instance variable.
