### ISSUE TITLE
Better Websocket api

### ISSUE THREAD

**Issue by andrewvc** [andrewvc/dripdrop#9]
websockets are the only stateful protocol dripdrop currently supports, and they're awkward, fix this.

**Comment by hedgehog** [comment]
Is there a reason DripDrop cannot include from an existing API?

sunshowers:
http://rainbows.rubyforge.org/sunshowers/
git://git.bogomips.org/sunshowers.git

em-websocket:
https://github.com/igrigorik/em-websocket
http://www.slideshare.net/ismasan/websockets-and-ruby-eventmachine

web-socket-ruby:
https://github.com/gimite/web-socket-ruby

LibWebSocket:
https://github.com/imanel/libwebsocket
http://imanel.org/2010/12/building-websocket-server-in-ruby/

**Comment by andrewvc** [comment]
Well, the idea with drip drop's web sockets (which are built on top of em-websocket, and use gimite for the specs) is to keep the api as close to the ZMQ ones as possible. It is actually pretty close to em-web socket's. Yeah, it is awkward, to a certain extent. the secret is to use closures judiciously, you actually want to embed your on_recv handlers inside on_open to track state. I'll add an example tonight. Once you see the pattern it's pretty easy to work with.

**Comment by hedgehog** [comment]
Okay sounds a reasonable starting point.  I think I don't quite get DripDrop just yet, since it is not clear that if I'm observing DripDrop's on_recv, why it has to be run inside its on_open.

**Comment by andrewvc** [comment]
It doesn't have to be, but by doing so instance variables declared in on_open are carried over to on_recv, and can be unique per-connection. See https://github.com/igrigorik/em-websocket/blob/master/examples/multicast.rb

for an example using raw em-websocket
